name: A11Y Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: a11y-${{ github.ref }}
  cancel-in-progress: true

jobs:
  a11y:
    name: A11Y
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright (a11y-only, Chromium)
        run: npx playwright test --project=chromium --reporter=github,html --grep "\[a11y\]"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a11y-playwright-report
          path: playwright-report
