name: E2E Desktop

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  call-core:
    uses: ./.github/workflows/core-tests.yml
    permissions:
      contents: write
    with:
      suite: desktop
      projects: "Desktop E2E"   # <-- matches your Playwright project name
