name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: E2E (non-a11y)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # If your tests need env vars, uncomment and set repo secrets
      # - name: Create .env
      #   run: |
      #     echo "VITE_CONTACT_ENDPOINT=${{ secrets.VITE_CONTACT_ENDPOINT }}" >> .env

      - name: Run Playwright (exclude a11y)
        run: npx playwright test --reporter=github,html --grep-invert "\[a11y\]"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-report
          path: playwright-report
