# .github/workflows/tests.yml
name: e2e-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # (Optional) .env if your site needs it
      # - name: Create .env
      #   run: echo "VITE_SOMETHING=${{ secrets.VITE_SOMETHING }}" >> .env

      - name: Run tests
        run: npx playwright test --reporter=html

      - name: Upload Playwright report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload axe accessibility report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: axe-a11y-report
          path: test-results/a11y
          if-no-files-found: ignore
