name: Visual (generate baselines)

on:
  workflow_dispatch:
    inputs:
      projects:
        description: "Comma-separated visual projects"
        required: false
        default: "visual-mobile,visual-desktop"

jobs:
  baselines:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Set stable env
        run: |
          echo "TZ=UTC" >> $GITHUB_ENV
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      # Sanity: show what Playwright projects CI sees
      - name: List Playwright projects
        run: npx playwright test --list

      # Clear any envs that could inject a regex filter
      - name: Clear PW_* env vars
        run: |
          unset PW_GREP || true
          unset PW_TEST_FILTER || true

      # Generate snapshots for each requested project.
      - name: Generate snapshots (update mode)
        env:
          CI: "true"
        run: |
          set -euo pipefail
          IFS=',' read -ra PROJ_ARR <<< "${{ github.event.inputs.projects }}"
          for p in "${PROJ_ARR[@]}"; do
            p_trimmed="$(echo "$p" | xargs)"
            if [ -z "$p_trimmed" ]; then
              echo "Skipping empty project entry"
              continue
            fi
            echo "Updating snapshots for project: $p_trimmed"
            npx playwright test --project="$p_trimmed" --update-snapshots
          done

      # Collect updated snapshots into a single folder for artifact upload
      - name: Collect snapshots
        if: always()
        run: |
          set -euo pipefail
          mkdir -p collected-snapshots
          find tests -type d -name "*-snapshots" -print0 | xargs -0 -I{} cp -r "{}" collected-snapshots/ || true
          find tests -type d -name "__snapshots__" -print0 | xargs -0 -I{} cp -r "{}" collected-snapshots/ || true
          echo "Collected snapshots:"
          ls -R collected-snapshots || true

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visual-snapshots-${{ github.run_id }}
          path: |
            collected-snapshots/**
            test-results/**
            playwright-report/**
          if-no-files-found: warn
