name: Visual (generate baselines)

on:
  workflow_dispatch:
    inputs:
      projects:
        description: "Comma-separated visual projects"
        required: false
        default: "visual-mobile,visual-desktop"

jobs:
  baselines:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Optional: build if your tests need it
      - name: Build (if needed)
        run: |
          if [ -f package.json ] && jq -er '.scripts.build' package.json >/dev/null 2>&1; then
            npm run build
          fi

      # Optional: start app if your tests expect it running already
      - name: Start app (if needed)
        run: |
          if jq -er '.scripts.start' package.json >/dev/null 2>&1; then
            nohup npm run start >/dev/null 2>&1 &
            sleep 3
          fi

      - name: Generate snapshots (update mode)
        env:
          CI: "true"
        run: |
          set -euo pipefail
          IFS=',' read -ra PROJ <<< "${{ github.event.inputs.projects }}"
          for p in "${PROJ[@]}"; do
            p_trimmed="$(echo "$p" | xargs)"
            if [ -n "$p_trimmed" ]; then
              echo "Updating snapshots for project: $p_trimmed"
              npx playwright test --project="$p_trimmed" --update-snapshots
            fi
          done

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visual-snapshots-${{ github.run_id }}
          path: |
            tests/**/-snapshots/**
            tests/**/__snapshots__/**
            test-results/**
            playwright-report/**
          if-no-files-found: warn
