# .github/workflows/update-visual-baselines.yml
name: Update visual baselines (PR)

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to open the PR against"
        required: true
        default: "main"
      commit_message:
        description: "Commit message for snapshot updates"
        required: false
        default: "chore: update visual baselines from CI"
      run_e2e:
        description: "Also run Desktop/Mobile E2E (no snapshot updates)"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-baselines:
    runs-on: ubuntu-latest
    env:
      # Force prod-like preview for more stable screenshots
      PLAYWRIGHT_WEB_SERVER_CMD: "npm run build && npm run preview -- --port 5173"
      PLAYWRIGHT_BASE_URL: "http://localhost:5173"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps

      # --- Update snapshots per visual project ---
      - name: Update Visual Desktop baselines
        run: npx playwright test --project="Visual Desktop" --update-snapshots

      - name: Update Visual Mobile baselines
        run: npx playwright test --project="Visual Mobile" --update-snapshots

      # (Optional) run E2E just to sanity check the preview build
      - name: Run Desktop E2E (sanity)
        if: ${{ inputs.run_e2e }}
        run: npx playwright test --project="Desktop E2E"
      - name: Run Mobile E2E (sanity)
        if: ${{ inputs.run_e2e }}
        run: npx playwright test --project="Mobile E2E"

      # Upload changed snapshots for quick inspection
      - name: Upload __screenshots__ artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: updated-snapshots
          path: |
            **/__screenshots__/**
            **/*-snapshots/**
          if-no-files-found: ignore
          retention-days: 7

      # Create a PR with the changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ inputs.commit_message }}
          title: ${{ inputs.commit_message }}
          body: |
            This PR updates visual baselines generated on Ubuntu CI.

            - Visual Desktop ✅
            - Visual Mobile ✅

            Review the updated images in the **updated-snapshots** artifact if needed.
          branch: chore/update-visual-baselines
          base: ${{ inputs.base_branch }}
          delete-branch: true
