name: Update visual baselines (PR)

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to open the PR against"
        required: true
        default: "main"
      commit_message:
        description: "Commit message for snapshot updates"
        required: false
        default: "chore: update visual baselines from CI"
      run_e2e:
        description: "Also run Desktop/Mobile E2E (no snapshot updates)"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-baselines:
    runs-on: ubuntu-latest
    env:
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps & browsers
        run: |
          npm ci
          # Install Playwright and dependencies, plus fonts for stable rendering
          sudo apt-get update
          sudo apt-get install -y fonts-liberation fonts-dejavu fonts-noto-core
          npx playwright install --with-deps

      # ── Use preview (prod-like) only for visual snapshots ──
      - name: Use preview server for visual suite
        run: |
          echo "PLAYWRIGHT_WEB_SERVER_CMD=npm run build && npm run preview -- --port 5173" >> $GITHUB_ENV
          echo "PLAYWRIGHT_BASE_URL=http://localhost:5173" >> $GITHUB_ENV
          echo "Using preview server for visual baselines:"
          echo "  PLAYWRIGHT_WEB_SERVER_CMD=$PLAYWRIGHT_WEB_SERVER_CMD"
          echo "  PLAYWRIGHT_BASE_URL=$PLAYWRIGHT_BASE_URL"

      - name: Update Visual Desktop baselines
        run: npx playwright test --project="Visual Desktop" --update-snapshots --workers=1

      - name: Update Visual Mobile baselines
        run: npx playwright test --project="Visual Mobile" --update-snapshots --workers=1

      # (Optional) switch back to dev server before E2E sanity runs
      - name: Clear preview overrides (back to dev) for E2E
        if: ${{ inputs.run_e2e }}
        run: |
          # Remove the overrides so playwright.config falls back to npm run dev
          sed -i '/PLAYWRIGHT_WEB_SERVER_CMD=/d' "$GITHUB_ENV" || true
          sed -i '/PLAYWRIGHT_BASE_URL=/d' "$GITHUB_ENV" || true
          echo "Cleared preview overrides; E2E will use dev server."

      - name: Run Desktop E2E (sanity)
        if: ${{ inputs.run_e2e }}
        run: npx playwright test --project="Desktop E2E"

      - name: Run Mobile E2E (sanity)
        if: ${{ inputs.run_e2e }}
        run: npx playwright test --project="Mobile E2E"

      # Upload updated snapshots (expected baselines)
      - name: Upload updated snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-snapshots
          path: |
            tests/**/__screenshots__/**
            tests/**/*-snapshots/**
          if-no-files-found: ignore
          retention-days: 7

      # Upload Playwright report (contains actual & diff images)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ inputs.commit_message }}
          title: ${{ inputs.commit_message }}
          body: |
            This PR updates **visual baselines** generated on Ubuntu CI (prod-like preview build).

            - Visual Desktop ✅
            - Visual Mobile ✅

            - **visual-snapshots** artifact: updated expected baselines
            - **playwright-report** artifact: actual/diff images for review
          branch: chore/update-visual-baselines
          base: ${{ inputs.base_branch }}
          delete-branch: true
